dist: trusty
language: php

php:
  - 7.0
  - 7.1
  - 7.2
  #- hhvm

env:
  matrix:
    - MONGODB=3.4.10
    - MONGODB=3.6.2
    - MONGODB=4.0.0

matrix:
  fast_finish: true

install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version


# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork
  - travis_retry pecl -q install -f mongodb-1.4.2
  #- echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sleep 10
  - composer self-update
  - travis_retry make deps-install-dev

script:
  #- vendor/bin/phpcs --standard=psr2 src/ todo enable it later
  - make unit-cov

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.xml
    fi
  - pkill mongod

after_success:
  - bash <(curl -s https://codecov.io/bash)

